### PR TITLE
Bowerify

### PR DESCRIPTION
**Pull request by bencates**

### CODE REVIEW

**Comment by jGleitz** [comment]
@bencates : I understand you’d like to see this package published on bower?

**Comment by jGleitz** [comment]
@system76 : Coming back to this, I just saw you already registered this project in bower. Are you planning to keep it up-to-date? Because otherwise I’d suggest transferring it to me to make sure it always contains the latest version.

**Comment by bencates** [comment]
I've unregistered our copy from Bower.  Name's all yours!

**Comment by jGleitz** [comment]
Alright. Package is now also available from bower. Thanks!

**Comment by bencates** [comment]
Oh, and thanks for the package!  Small feature, but it scratched a big itch for our support team.

**Pull request merged**
